### ISSUE TITLE
Networkx version

### ISSUE THREAD

**Issue by hyliush** [pmehler/Exploring-SIS-Model-on-Computer-Generated-Networks#1]
Hello, thank you for sharing.  Can you tell me the version of Networkx you used? The code is not compatible on version 2.4.

**Comment by pmehler** [comment]
Hello!  I used Networkx version 2.2 when writing this script!

What error are you getting?

**Comment by hyliush** [comment]
Thanks for your reply. An error 'MultiGraph' object has no attribute 'node' will  arise in version 2.4. It has been solved if I use 2.2. Thanks for your sharing again.
